name: multilingual_chat
description: A Multilingual chat app

# Prevent accidental publishing to pub.dev.
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  animated_text_kit: ^4.2.1
  cloud_firestore: ^3.1.4
  firebase_auth: ^3.3.3
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  flutter_spinkit: ^5.1.0
  flutter_tts: ^3.3.3
  font_awesome_flutter: ^9.2.0
  google_sign_in: ^5.2.1
  html_unescape: ^2.0.0
  provider: ^6.0.1
  speech_recognition: ^0.3.0+1
  translator: ^0.1.7

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^1.0.0

flutter:
  uses-material-design: true

  # Enable generation of localized Strings from arb files.
  generate: true

  assets:
    # Add assets from the images directory to the application.
    - assets/images/
  fonts:
      - family: SF
        fonts:
          - asset: assets/fonts/SF-Regular.otf
